// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kgR1njfXV2HHLGn28Yi0ai0hTJZ3cnU',
    appId: '1:1007903507898:web:e05afea692a684df714983',
    messagingSenderId: '1007903507898',
    projectId: 'travel-app-ef933',
    authDomain: 'travel-app-ef933.firebaseapp.com',
    storageBucket: 'travel-app-ef933.firebasestorage.app',
    measurementId: 'G-D9NFC9KGYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDPmH0rUgtc7A8C5pX2oY0sJz5-tRcqM',
    appId: '1:1007903507898:android:e275c6e80214654f714983',
    messagingSenderId: '1007903507898',
    projectId: 'travel-app-ef933',
    storageBucket: 'travel-app-ef933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2z-QtMSFsi-yWaX0402gNGQYTNLUALQ',
    appId: '1:1007903507898:ios:d523cc83d4482140714983',
    messagingSenderId: '1007903507898',
    projectId: 'travel-app-ef933',
    storageBucket: 'travel-app-ef933.firebasestorage.app',
    iosClientId: '1007903507898-bp9h24lpvdpn4c5sbmud314dsdd4nc3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2kgR1njfXV2HHLGn28Yi0ai0hTJZ3cnU',
    appId: '1:1007903507898:web:fa88209891bef54d714983',
    messagingSenderId: '1007903507898',
    projectId: 'travel-app-ef933',
    authDomain: 'travel-app-ef933.firebaseapp.com',
    storageBucket: 'travel-app-ef933.firebasestorage.app',
    measurementId: 'G-JLKRCDN5TY',
  );
}
